foreground              #dfe3e8
background              #101417
selection_foreground    #101417
selection_background    #94cdf7
cursor                  #94cdf7
cursor_text_color       #101417
url_color               #b7c9d9
active_border_color     #94cdf7
inactive_border_color   #1c2024
bell_border_color       #ffb4ab
active_tab_foreground   #101417
active_tab_background   #94cdf7
inactive_tab_foreground #dfe3e8
inactive_tab_background #1c2024
tab_bar_background      #41474d
color0  #41474d
color8  #1c2024
color1  #ffb4ab
color9  #ffb4ab
color2  #cec0e8
color10 #cec0e8
color3  #4b4163
color11 #4b4163
color4  #b7c9d9
color12 #b7c9d9
color5  #94cdf7
color13 #94cdf7
color6  #b7c9d9
color14 #b7c9d9
color7  #c1c7ce
color15 #dfe3e8
