foreground #ECEFF4
background #2E3440
cursor #88C0D0
cursor_text_color #2E3440
selection_background #434C5E
selection_foreground #ECEFF4
color0 #3B4252
color1 #BF616A
color2 #A3BE8C
color3 #EBCB8B
color4 #88C0D0
color5 #88C0D0
color6 #8FBCBB
color7 #4C566A
color8 #4C566A
color9 #BF616A
color10 #A3BE8C
color11 #EBCB8B
color12 #88C0D0
color13 #88C0D0
color14 #8FBCBB
color15 #ECEFF4
