layerrule = blur on, match:namespace rofi
layerrule = ignore_alpha 0.2, match:namespace rofi
#layerrule = blur on, match:namespace rofi
layerrule = blur on, match:namespace rofi-select
layerrule = blur on, match:namespace dmenu
layerrule = blur on, match:namespace waybar
layerrule = ignore_alpha 0.2, match:namespace waybar
layerrule = blur on, match:namespace swaync-control-center
layerrule = ignore_alpha 0.2, match:namespace swaync-control-center
layerrule = blur on, match:namespace qs-keybinds
layerrule = ignore_alpha 0.2, match:namespace qs-keybinds
layerrule = blur on, match:namespace swaync-notification-window
layerrule = ignore_alpha 0.2, match:namespace swaync-notification-window

