# HyDE ARM window rules
windowrule = opacity 0.90 0.90 1, match:class ^(firefox)$
windowrule = opacity 0.80 0.80 1, match:class ^(kitty)$
windowrule = opacity 0.80 0.80 1, match:class ^(thunar)$
#windowrule = bordercolor rgba(00000000), match:class = kitty
#windowrule = float, class:^(pavucontrol)$
#windowrule = float, class:^(nm-connection-editor)$
#windowrule = float, class:^(thunar)$
#windowrule = float, class:^(nwg-look)$
#windowrule = size 900 600, class:^(thunar)$
#windowrule = center, class:^(thunar)$
layerrule = blur on, match:namespace rofi
layerrule = ignore_alpha 0.2, match:namespace rofi
#layerrule = blur on, match:namespace rofi
#layerrule = blur on, match:namespace rofi-select
#layerrule = blur on, match:namespace dmenu
#layerrule = blur on, match:namespace waybar
#layerrule = ignore_alpha 0.2, match:namespace waybar
#layerrule = blur on, match:namespace swaync-control-center
#layerrule = ignorezero on, match:namespace swaync-control-center

#layerrule = blur on, match:namespace swaync-notification-window
#layerrule = ignorezero on, match:namespace swaync-notification-window


# Scratchpad terminal
#windowrule = float,         class:^(kitty-scratchpad)$
#windowrule = size 70% 40%,  class:^(kitty-scratchpad)$
#windowrule = center,        class:^(kitty-scratchpad)$
#windowrule = animation slidedown, class:^(kitty-scratchpad)$
#windowrule = workspace special:scratchpad silent, class:^(kitty-scratchpad)$
