-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local ANIMATION = "theme"

local ANIMATION_PATH = "~/.config/hypr/animations/theme.lua"

-- source = $ANIMATION_PATH -> requires manual conversion
-- local _ANIMATION_PATH = require("_ANIMATION_PATH")
-- TODO: convert $ANIMATION_PATH to .lua and use require()
