-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local mainMod = "ALT"

hl.bind("ALT" .. " + " .. "RETURN", hl.dsp.exec_cmd("kitty"))

hl.bind("ALT" .. " + " .. "Q", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "C", hl.dsp.exec_cmd("qs ipc -p/usr/share/chillpill-shell call controlCenter toggle"))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "V", hl.dsp.exec_cmd("qs ipc -p/usr/share/chillpill-shell call cliphist toggle"))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "B", hl.dsp.exec_cmd("qs ipc -p/usr/share/chillpill-shell call miniDashboard toggle"))

hl.bind(mainMod .. " + " .. "D", hl.dsp.exec_cmd("qs ipc -p/usr/share/chillpill-shell call appLauncher toggle"))

hl.bind(mainMod .. " + " .. "W", hl.dsp.exec_cmd("qs ipc -p/usr/share/chillpill-shell call wallpaperSwitcher toggle"))

hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("$EXPLORER"))

hl.bind(mainMod .. " + " .. "B", hl.dsp.exec_cmd("$BROWSER"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "left", { direction = "l" })

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "right", { direction = "r" })

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "up", { direction = "u" })

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "down", { direction = "d" })

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

hl.bind("SUPER" .. " + " .. "D", hl.dsp.exec_cmd("bash ~/.config/hypr/scripts/rofi-shell-switch.sh"))
