-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    general = {
        lock_cmd = "bash ~/.config/hypr/scripts/lock.sh",
        before_sleep_cmd = "bash ~/.config/hypr/scripts/lock.sh",
        after_sleep_cmd = "hyprctl dispatch dpms on",
    },
})

hl.config({
    listener = {
        timeout = 300,
        -- 5 min — lock screen
        on_timeout = "fish -c hyprlock",
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output

hl.config({
    listener = {
        timeout = 360,
        -- 6 min — turn off display
        on_timeout = "hyprctl dispatch dpms off",
        on_resume = "hyprctl dispatch dpms on",
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output
