-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- HyDE ARM window rules

hl.window_rule({
    name  = "opacity_0_90_0_90_1",
    match = {
        class = "^(firefox)$",
    },
    opacity = "0.90 0.90 1",
})

hl.window_rule({
    name  = "opacity_0_80_0_80_1",
    match = {
        class = "^(kitty)$",
    },
    opacity = "0.80 0.80 1",
})

hl.window_rule({
    name  = "opacity_0_80_0_80_1",
    match = {
        class = "^(thunar)$",
    },
    opacity = "0.80 0.80 1",
})

--windowrule = bordercolor rgba(00000000), match:class = kitty

--windowrule = float, class:^(pavucontrol)$

--windowrule = float, class:^(nm-connection-editor)$

--windowrule = float, class:^(thunar)$

--windowrule = float, class:^(nwg-look)$

--windowrule = size 900 600, class:^(thunar)$

--windowrule = center, class:^(thunar)$

hl.layer_rule({
    match = {
        namespace = "rofi",
    },
    blur = true,
})

hl.layer_rule({
    match = {
        namespace = "match:namespace rofi",
    },
    ignore_alpha = 0.2,
})

--layerrule = blur on, match:namespace rofi

--layerrule = blur on, match:namespace rofi-select

--layerrule = blur on, match:namespace dmenu

--layerrule = blur on, match:namespace waybar

--layerrule = ignore_alpha 0.2, match:namespace waybar

--layerrule = blur on, match:namespace swaync-control-center

--layerrule = ignorezero on, match:namespace swaync-control-center

--layerrule = blur on, match:namespace swaync-notification-window

--layerrule = ignorezero on, match:namespace swaync-notification-window

-- Scratchpad terminal

--windowrule = float,         class:^(kitty-scratchpad)$

--windowrule = size 70% 40%,  class:^(kitty-scratchpad)$

--windowrule = center,        class:^(kitty-scratchpad)$

--windowrule = animation slidedown, class:^(kitty-scratchpad)$

--windowrule = workspace special:scratchpad silent, class:^(kitty-scratchpad)$
