-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Crimson Twilight — Hyprland theme config

-- Cinematic anime, dramatic dusk

hl.config({
    general = {
        border_size = 2,
        gaps_in = 6,
        gaps_out = 12,
        col = {
            active_border = { colors = { "rgba(E64A45ff)", "rgba(B84E60ff)" }, angle = 45 },
            inactive_border = "rgba(1A1116ff)",
        },
    },
})

hl.config({
    decoration = {
        rounding = 14,
        active_opacity = 1.0,
        inactive_opacity = 0.96,
        blur = {
            enabled = true,
            size = 8,
            passes = 3,
            vibrancy = 0.15,
            vibrancy_darkness = 0.1,
            contrast = 0.9,
            brightness = 0.85,
            noise = 0.008,
            new_optimizations = true,
            xray = false,
        },
        shadow = {
            enabled = true,
            range = 20,
            render_power = 3,
            color = "rgba(E64A4530)",
            color_inactive = "rgba(1A111688)",
        },
    },
})
