# HyDE ARM — theme.conf
# Updated by theme-switch.sh

general {
    gaps_in = 3
    gaps_out = 8
    border_size = 2
    col.active_border = rgba(CBA6F7ff) rgba(89B4FAff) 45deg
    col.inactive_border = rgba(313244cc) rgba(1E1E2Ecc) 45deg
    layout = dwindle
    resize_on_border = true
}

group {
    col.border_active = rgba(CBA6F7ff) rgba(89B4FAff) 45deg
    col.border_inactive = rgba(313244cc) rgba(1E1E2Ecc) 45deg
}

decoration {
    rounding = 10
    shadow:enabled = false
    blur {
        enabled = true
        size = 5
        passes = 2
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
}

#layerrule = blur, waybar
#layerrule = ignorezero, waybar
#layerrule = blur, rofi
#layerrule = ignorezero, rofi
#layerrule = blur, swaync-control-center
#layerrule = ignorezero, swaync-control-center

#layerrule = blur, swaync-notification-window
#layerrule = ignorezero, swaync-notification-window
layerrule = blur on, match:namespace qs-overview
layerrule = ignore_alpha 0.2, match:namespace qs-overview
layerrule = blur on, match:namespace qs-settings
layerrule = ignore_alpha 0.2, match:namespace qs-settings
layerrule = blur on, match:namespace qs-welcome
layerrule = ignore_alpha 0.2, match:namespace qs-welcome
layerrule = blur on, match:namespace qs-theme-picker
layerrule = ignore_alpha 0.2, match:namespace qs-theme-picker
layerrule = blur on, match:namespace qs-wallpaper-picker
layerrule = ignore_alpha 0.2, match:namespace qs-wallpaper-picker
layerrule = blur on, match:namespace qs-launcher
layerrule = ignore_alpha 0.2, match:namespace qs-launcher
layerrule = blur on, match:namespace qs-applet
layerrule = ignore_alpha 0.2, match:namespace qs-applet
layerrule = blur on, match:namespace qs-notch
layerrule = ignore_alpha 0.2, match:namespace qs-notch
