-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- HyDE ARM — hyprland.conf

-- VMware Fusion aarch64

--env = PATH,$HOME/.local/bin:$PATH

-- ── Allow Native SVGA Atomic Modesetting ─────────────────────────────────────

-- DO NOT set NO_ATOMIC or ALLOW_SOFTWARE here. Let it run natively.

--env = AQ_DRM_DEVICES,/dev/dri/card0

--env = WLR_RENDERER,gles2

-- ── Force the Toolkits to match the SVGA Hardware Context ────────────────────

--env = GDK_BACKEND,wayland

--env = QT_QPA_PLATFORM,wayland

--env = KITTY_DISABLE_WAYLAND,0

-- ── Safe Mesa Core Profile Injection ─────────────────────────────────────────

--env = MESA_GL_VERSION_OVERRIDE,3.3

--env = MESA_GLSL_VERSION_OVERRIDE,330

--env = QT_QUICK_BACKEND,opengl

-- ── Hardware Cursor Toggle (Keep this one enabled for VM syncing) ────────────

--env = WLR_NO_HARDWARE_CURSORS,1

-- ── Identify and Force the Physical VMware SVGA Card ────────────────────────

--env = AQ_DRM_DEVICES,/dev/dri/card0:/dev/dri/renderD128

--env = AQ_NO_KMS_REQUIREMENT,1

-- ── Force Mesa to use the Hardware SVGA Translation Layer ─

-- ── VMware ARM software rendering ─────────────────────────────────────────────

--env = WLR_RENDERER,pixman

hl.env("WLR_RENDERER_ALLOW_SOFTWARE", 1)

hl.env("WLR_DRM_NO_ATOMIC", 1)

hl.env("LIBGL_ALWAYS_SOFTWARE", 1)

hl.env("WLR_NO_HARDWARE_CURSORS", 1)

--env = PATH,$HOME/.local/share/vm-wrappers:$PATH

--export PATH="$HOME/.local/bin:$PATH"

-- ── Wayland env ───────────────────────────────────────────────────────────────

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")

hl.env("XDG_SESSION_TYPE", "wayland")

hl.env("XDG_SESSION_DESKTOP", "Hyprland")

hl.env("QT_QPA_PLATFORM", "wayland;xcb")

hl.env("GDK_BACKEND", "wayland,x11,*")

hl.env("MOZ_ENABLE_WAYLAND", 1)

hl.env("XCURSOR_SIZE", 24)

hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")

-- ── Sourced configs (HyDE structure) ─────────────────────────────────────────

-- source = ~/.config/hypr/themes/theme.conf -> requires manual conversion
local theme = require("themes.theme")
-- TODO: convert ~/.config/hypr/themes/theme.conf to .lua and use require()

-- source = ~/.config/hypr/animations.conf -> requires manual conversion
local animations = require("animations")
-- TODO: convert ~/.config/hypr/animations.conf to .lua and use require()

-- source = ~/.config/hypr/current_profile_binds.conf -> requires manual conversion
local current_profile_binds = require("current_profile_binds")
-- TODO: convert ~/.config/hypr/current_profile_binds.conf to .lua and use require()

--source = ~/.config/hypr/keybindings.conf

-- source = ~/.config/hypr/windowrules.conf -> requires manual conversion
local windowrules = require("windowrules")
-- TODO: convert ~/.config/hypr/windowrules.conf to .lua and use require()

-- source = ~/.config/hypr/monitors.conf -> requires manual conversion
local monitors = require("monitors")
-- TODO: convert ~/.config/hypr/monitors.conf to .lua and use require()

-- source = ~/.config/hypr/userprefs.conf -> requires manual conversion
local userprefs = require("userprefs")
-- TODO: convert ~/.config/hypr/userprefs.conf to .lua and use require()

-- source = ~/.config/hypr/layerrules.conf -> requires manual conversion
local layerrules = require("layerrules")
-- TODO: convert ~/.config/hypr/layerrules.conf to .lua and use require()
local plugins = require("plugins")
-- ── Autostart ─────────────────────────────────────────────────────────────────










--exec-once = qs -c ~/.config/quickshell/applets

--exec-once = qs -c ~/.config/quickshell/theme-switcher

--exec-once = qs -c ~/.config/quickshell/wallpaper-picker

--exec-once = qs -c ~/.config/quickshell/launcher

-- Zen live theme watcher
 



-- Glass preset

--plugin:hyprglass {

--    blur_strength = 2.0

--    blur_iterations = 3#

--

--    chromatic_aberration = 0.8

--    fresnel_strength = 0.8

--    edge_thickness = 0.08#

--

--    # Replace with your preferred tint color if desired.

--    # The Lua version uses tint(colors.bg0, 0.12), which isn't supported in legacy configs.

--    tint_color = rgba(0000001F)##

-- lens_distortion = 0.9##

--brightness = 1.0

--contrast = 1.7

--saturation = 1.0

--vibrancy = 0.8

--vibrancy_darkness = 1.0

--adaptive_boost = 0.5

--}

-- .config/hypr/hyprland.conf

--plugin {

--    scrolloverview {

--#        gesture_distance = 300 # how far is the "max" for the gesture

--##        scale = 0.5 # preferred overview scale

--      workspace_gap = 100

--#      layout = vertical # vertical or horizontal

--    wallpaper = 0 # 0: global only, 1: per-workspace only, 2: both

--    blur = false # blur only the main overview wallpaper#

--

--        shadow {

--            enabled = false

--            range = 50

--            render_power = 3

--            color = rgba(1a1a1aee)

--        }

--    }

--}

-- nothingshell

--source = /home/nihal/.config/quickshell/nothingshell/hypr/nothingshell.conf

-- Generated binds are stored in ~/.config/tide-island/hyprland-shortcuts.conf.

-- They call Quickshell IPC and can also be reused from your own scripts.

-- source = /home/nihal/.config/tide-island/hyprland-shortcuts.conf -> requires manual conversion
-- local hyprland_shortcuts = require("tide_island.hyprland_shortcuts")
-- TODO: convert /home/nihal/.config/tide-island/hyprland-shortcuts.conf to .lua and use require()

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("bash ~/.config/hypr/scripts/startup.sh")
    hl.exec_cmd("swaync")
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
    hl.exec_cmd("wl-paste --watch cliphist store")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("hyprctl setcursor Bibata-Modern-Ice 24")
    hl.exec_cmd("qs -c ~/.config/quickshell")
    hl.exec_cmd("qs -c ~/.config/quickshell/keybinds")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("/home/nihal/.config/zen/scripts/zen-css-watch.sh")
    hl.exec_cmd("sh -c \"echo 'waybar' > ~/.config/hypr/bar/active-bar\"")
    hl.exec_cmd("qs -c overview")
end)
