-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Ambxst mode — only shell switcher active

-- All HyDE ARM keybinds suspended

-- Shell switcher always available

hl.bind("$mainMod + CTRL" .. " + " .. "S", hl.dsp.exec_cmd("bash ~/.config/hypr/scripts/shell-switch.sh"))
