-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--hl.layer_rule({
  --  match = {
    --    namespace = "match:namespace rofi",
    --},
    --blur = "on",
--})

hl.layer_rule({
    match = {
        namespace = "match:namespace rofi",
    },
    ignore_alpha = 0.2,
})

--layerrule = blur on, match:namespace rofi

hl.layer_rule({
    match = {
        namespace = "rofi-select",
    },
    blur = true,
})

hl.layer_rule({
    match = {
        namespace = "dmenu",
    },
    blur = true,
})

hl.layer_rule({
    match = {
        namespace = "waybar",
    },
    blur = true,
})

hl.layer_rule({
    match = {
        namespace = "match:namespace waybar",
    },
    ignore_alpha = 0.2,
})

hl.layer_rule({
    match = {
        namespace = "swaync-control-center",
    },
    blur = true,
})

hl.layer_rule({
    match = {
        namespace = "match:namespace swaync-control-center",
    },
    ignore_alpha = 0.2,
})

hl.layer_rule({
    match = {
        namespace = "qs-keybinds",
    },
    blur = true,
})

hl.layer_rule({
    match = {
        namespace = "match:namespace qs-keybinds",
    },
    ignore_alpha = 0.2,
})

hl.layer_rule({
    match = {
        namespace = "swaync-notification-window",
    },
    blur = true,
})

hl.layer_rule({
    match = {
        namespace = "match:namespace swaync-notification-window",
    },
    ignore_alpha = 0.2,
})
