-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ~/.config/hypr/tide_island_binds.conf

-- Adapted for VMware Fusion (using ALT instead of SUPER/macOS shortcuts)

hl.bind("ALT" .. " + " .. "TAB", hl.dsp.exec_cmd("/usr/bin/quickshell ipc --any-display -p/usr/share/tide-island call overview toggle"))

hl.bind("ALT" .. " + " .. "right", hl.dsp.exec_cmd("/usr/bin/quickshell ipc --any-display -p/usr/share/tide-island call tide swipeRight"))

hl.bind("ALT" .. " + " .. "left", hl.dsp.exec_cmd("/usr/bin/quickshell ipc --any-display -p/usr/share/tide-island call tide swipeLeft"))

hl.bind("ALT" .. " + " .. "down", hl.dsp.exec_cmd("/usr/bin/quickshell ipc --any-display -p/usr/share/tide-island call tide showClock"))

hl.bind("ALT" .. " + " .. "M", hl.dsp.exec_cmd("/usr/bin/quickshell ipc --any-display -p/usr/share/tide-island call tide togglePlayer"))

hl.bind("ALT" .. " + " .. "C", hl.dsp.exec_cmd("/usr/bin/quickshell ipc --any-display -p/usr/share/tide-island call tide toggleControlCenter"))

hl.bind("ALT" .. " + " .. "N", hl.dsp.exec_cmd("/usr/bin/quickshell ipc --any-display -p/usr/share/tide-island call tide toggleNotificationCenter"))

hl.bind("ALT + SHIFT" .. " + " .. "G", hl.dsp.exec_cmd("/usr/bin/quickshell ipc --any-display -p/usr/share/tide-island call tide toggleWallpaperPicker"))

hl.bind("ALT" .. " + " .. "slash", hl.dsp.exec_cmd("/usr/bin/quickshell ipc --any-display -p/usr/share/tide-island call tide toggleApplicationLauncher"))

hl.bind("ALT" .. " + " .. "F", hl.dsp.exec_cmd("/usr/bin/quickshell ipc --any-display -p/usr/share/tide-island call island toggle"))
