-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Astra Bloom — Hyprland theme config

-- Bioluminescent Alien Forest

hl.config({
    general = {
        border_size = 2,
        gaps_in = 6,
        gaps_out = 12,
        col = {
            active_border = { colors = { "rgba(FF9E9Dff)", "rgba(D381A1ff)" }, angle = 45 },
            inactive_border = "rgba(4A2840ff)",
        },
    },
})

hl.config({
    decoration = {
        rounding = 14,
        active_opacity = 1.0,
        inactive_opacity = 0.96,
        blur = {
            enabled = true,
            size = 10,
            passes = 4,
            vibrancy = 0.2,
            vibrancy_darkness = 0.1,
            contrast = 0.9,
            brightness = 0.8,
            noise = 0.01,
            new_optimizations = true,
            xray = false,
        },
        shadow = {
            enabled = true,
            range = 24,
            render_power = 3,
            color = "rgba(FF9E9D22)",
            color_inactive = "rgba(1A0F1F88)",
        },
    },
})
