-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Solarized Dark — Hyprland theme config

hl.config({
    general = {
        border_size = 2,
        gaps_in = 6,
        gaps_out = 12,
        col = {
            active_border = { colors = { "rgba(268BD2ff)", "rgba(2AA198ff)" }, angle = 45 },
            inactive_border = "rgba(073642ff)",
        },
    },
})

hl.config({
    decoration = {
        rounding = 12,
        active_opacity = 1.0,
        inactive_opacity = 0.97,
        blur = {
            enabled = true,
            size = 7,
            passes = 3,
            vibrancy = 0.1,
            contrast = 0.9,
            brightness = 0.85,
            noise = 0.008,
            new_optimizations = true,
            xray = false,
        },
        shadow = {
            enabled = true,
            range = 18,
            render_power = 3,
            color = "rgba(268BD225)",
            color_inactive = "rgba(002B3688)",
        },
    },
})
