-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua

---@module 'hl'

-- HyDE ARM — theme.conf
-- Updated by theme-switch.sh

hl.config({
    general = {
        gaps_in = 3,
        gaps_out = 8,
        border_size = 2,
        layout = "dwindle",
        resize_on_border = true,
        col = {
            active_border = { colors = { "rgba(CBA6F7ff)", "rgba(89B4FAff)" }, angle = 45 },
            inactive_border = { colors = { "rgba(313244cc)", "rgba(1E1E2Ecc)" }, angle = 45 },
        },
    },
})

hl.config({
    group = {
        col = {
            border_active = { colors = { "rgba(CBA6F7ff)", "rgba(89B4FAff)" }, angle = 45 },
            border_inactive = { colors = { "rgba(313244cc)", "rgba(1E1E2Ecc)" }, angle = 45 },
        },
    },
})

hl.config({
    decoration = {
        rounding = 10,
        shadow = {
            enabled = false,
        },
        blur = {
            enabled = true,
            size = 5,
            passes = 2,
            new_optimizations = true,
            ignore_opacity = true,
            xray = false,
        },
    },
})

-- ── Active Glass Blur Window Layer Configurations ───────────────────────────

-- Overview Panel
hl.layer_rule({ match = { namespace = "qs-overview" }, blur = true })
hl.layer_rule({ match = { namespace = "qs-overview" }, ignore_alpha = 0.2 })

-- Settings Menu
hl.layer_rule({ match = { namespace = "qs-settings" }, blur = true })
hl.layer_rule({ match = { namespace = "qs-settings" }, ignore_alpha = 0.2 })

-- Welcome Panel
hl.layer_rule({ match = { namespace = "qs-welcome" }, blur = true })
hl.layer_rule({ match = { namespace = "qs-welcome" }, ignore_alpha = 0.2 })

-- Theme Applet Selector
hl.layer_rule({ match = { namespace = "qs-theme-picker" }, blur = true })
hl.layer_rule({ match = { namespace = "qs-theme-picker" }, ignore_alpha = 0.2 })

-- Dynamic Wallpaper Applet
hl.layer_rule({ match = { namespace = "qs-wallpaper-picker" }, blur = true })
hl.layer_rule({ match = { namespace = "qs-wallpaper-picker" }, ignore_alpha = 0.2 })

-- Application Launcher
hl.layer_rule({ match = { namespace = "qs-launcher" }, blur = true })
hl.layer_rule({ match = { namespace = "qs-launcher" }, ignore_alpha = 0.2 })

-- Base Wrapper Applets
hl.layer_rule({ match = { namespace = "qs-applet" }, blur = true })
hl.layer_rule({ match = { namespace = "qs-applet" }, ignore_alpha = 0.2 })

-- Nothing OS Top Notch Bar Layout
hl.layer_rule({ match = { namespace = "qs-notch" }, blur = true })
hl.layer_rule({ match = { namespace = "qs-notch" }, ignore_alpha = 0.2 })
