-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local lock_bg = "rgb(161217)"

local lock_fg = "rgb(e9e0e7)"

local lock_acc = "rgb(e3b7f4)"
